---
driver:
  name: docker
  use_sudo: false
  require_chef_omnibus: false
  cap_add:
    - SYS_ADMIN
  run_options:
    tmpfs:
      - /run
      - /run/lock
    volume:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    stop-signal: SIGRTMIN+3

provisioner:
  name: ansible_push
  ansible_config: test/ansible.cfg
  verbose: v
  diff: true
  chef_bootstrap_url: nil

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver_config:
      image: bdclark/ubuntu-1804-test:latest
      run_command: /lib/systemd/systemd
  - name: ubuntu-16.04
    driver_config:
      image: bdclark/ubuntu-1604-test:latest
      run_command: /lib/systemd/systemd
  - name: centos-7
    driver_config:
      image: bdclark/centos-7-test:latest
      run_command: /lib/systemd/systemd
    provisioner:
      extra_vars:
      consul_dnsmasq_networkmanager_enabled: true

suites:
  - name: default
    provisioner:
      playbook: test/integration/default/playbook.yml
  - name: repo
    provisioner:
      playbook: test/integration/tls/playbook.yml
