---
- name: update base config - TLS CA cert_file
  set_fact:
    consul_base_config: "{{ consul_base_config | combine({'ca_file': consul_conf_dir + '/ca.crt' }) }}"
  when: consul_ca_content is not none and consul_ca_content | length > 0

- name: update base config - TLS cert/key
  set_fact:
    consul_base_config: "{{ consul_base_config | combine({'cert_file': consul_conf_dir + '/consul.crt', 'key_file': consul_conf_dir + '/consul.key' }) }}"
  when: >
    consul_cert_content is not none and consul_cert_content | length > 0
    and consul_key_content is not none and consul_key_content | length > 0

- name: set consul configuration
  set_fact:
    consul_config: "{{ consul_base_config | combine(consul_config, recursive=True) }}"

- name: create service group
  group:
    name: "{{ consul_group }}"
    system: true
  when: consul_user_managed | bool

- name: create service user
  user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    createhome: false
    system: true
    shell: /bin/false
    comment: Consul service user
  when: consul_user_managed | bool

- name: create conf directory
  file:
    state: directory
    path: "{{ consul_conf_dir }}"
    owner: "{{ consul_conf_dir_owner }}"
    group: "{{ consul_group }}"
    mode: "{{ consul_conf_dir_mode }}"

- name: create data directory
  file:
    state: directory
    path: "{{ consul_data_dir }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0750"

- name: write config file
  template:
    src: "{{ consul_config_template }}"
    dest: "{{ consul_conf_dir }}/config.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0640"
  notify:
    - restart consul

- name: create TLS key
  no_log: true
  copy:
    content: "{{ consul_key_content }}"
    dest: "{{ consul_config.key_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0600"
  when: consul_key_content is not none

- name: create TLS cert
  no_log: true
  copy:
    content: "{{ consul_cert_content }}"
    dest: "{{ consul_config.cert_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0600"
  when: consul_cert_content is not none

- name: create TLS CA cert
  no_log: true
  copy:
    content: "{{ consul_ca_content }}"
    dest: "{{ consul_config.ca_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0600"
  when: consul_ca_content is not none

- name: systemd init script
  template:
    src: "{{ consul_systemd_template }}"
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload systemd
    - restart consul
