---
- name: install dnsmasq
  package:
    name: dnsmasq
    state: present

- name: ensure dnsmasq.d directory
  file:
    state: directory
    dest: /etc/NetworkManager/dnsmasq.d

- name: set consul dns server address
  set_fact:
    consul_dns_ip: "{{ consul_config.addresses.dns | split(':')[0] }}"
  when: consul_config.addresses is defined and consul_config.addresses.dns

- name: set consul dns server port
  set_fact:
    consul_dns_port: "{{ consul_config.ports.dns }}"
  when: consul_config.ports is defined and consul_config.ports.dns

- name: configure dnsmasq for consul domain
  copy:
    content: "server=/{{ consul_config.domain | default('consul') }}/{{ consul_dns_ip | default(consul_config.client_addr) }}\
      #{{ consul_dns_port | default(8600) }}"
    dest: /etc/NetworkManager/dnsmasq.d/10-consul
  notify: restart dnsmasq

- name: enable NetworkManager dnsmasq plugin
  lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    insertafter: \[main\]
    regexp: ^dns=
    line: dns=dnsmasq
    state: present
  when: ansible_os_family == 'RedHat' and consul_dnsmasq_networkmanager_enabled
  notify: restart networkmanager

- name: stop/disable dnsmasq (NetworkManager)
  service:
    name: dnsmasq
    state: stopped
    enabled: false
  when: ansible_os_family == 'RedHat' and consul_dnsmasq_networkmanager_enabled
