---
- name: install unzip
  package:
    name: unzip
    state: present

- name: ensure consul directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ consul_install_dir }}"
    - "{{ consul_bin_dir }}"

- name: download consul checksum file
  get_url:
    url: "{{ consul_checksum_url }}"
    dest: "{{ consul_install_dir }}/{{ consul_checksum_file }}"

- block:
    - name: write hashicorp gpg key file
      copy:
        src: hashicorp.asc
        dest: /etc/hashicorp.asc
        owner: root
        group: root
        mode: 0644

    - name: import hashicorp gpg key
      command: gpg --import /etc/hashicorp.asc
      register: consul_gpg_key_imported
      changed_when: false

    - name: download consul checksum signature file
      get_url:
        url: "{{ consul_signature_url }}"
        dest: "{{ consul_install_dir }}/{{ consul_signature_file }}"

    - name: verify checksum file
      command: gpg --batch --verify {{ consul_install_dir }}/{{ consul_signature_file }} {{ consul_install_dir }}/{{ consul_checksum_file }}
      changed_when: false
  when: consul_verify_checksum_signature | bool

- name: get checksum of consul zip
  command: grep {{ consul_zip }} {{ consul_install_dir }}/{{ consul_checksum_file }}
  register: consul_checksum
  changed_when: false

- block:
    - name: download consul zip
      get_url:
        url: "{{ consul_zip_url }}"
        dest: "{{ consul_install_dir }}/{{ consul_zip }}"
        checksum: "sha256:{{ consul_checksum.stdout.split(' ') | first }}"

    - name: extract consul zip
      unarchive:
        src: "{{ consul_install_dir }}/{{ consul_zip }}"
        dest: "{{ consul_install_dir }}"
        remote_src: true
        creates: "{{ consul_install_dir }}/consul"
        owner: root
        group: root
        mode: 0755
      notify: restart consul

    - name: symlink consul binary
      file:
        state: link
        src: "{{ consul_install_dir }}/consul"
        dest: "{{ consul_bin_dir }}/consul"
      notify: restart consul
  when: not ansible_check_mode
