---
- name: configure consul services
  template:
    src: "{{ consul_service_template }}"
    dest: '{{ consul_conf_dir }}/service-{{ item.key }}.json'
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  with_dict: "{{ consul_services | combine(consul_services_group, recursive=true) | combine(consul_services_host, recursive=true) }}"
  notify: reload consul

- name: configure consul bulk services
  template:
    src: "{{ consul_bulk_services_template }}"
    dest: "{{ consul_conf_dir }}/services.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  when: consul_services_bulk | length > 0
  notify: reload consul

- name: remove bulk services config file
  file:
    path: "{{ consul_conf_dir }}/services.json"
    state: absent
  when: consul_services_bulk | length == 0
