---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart consul
  service:
    name: consul
    state: restarted
  when: consul_service_restart_on_update and consul_service_enabled and consul_service_state == 'started'

- name: reload consul
  service:
    name: consul
    state: reloaded
  when: consul_service_enabled and consul_service_state == 'started'
